# handle .mdeprc and exact docker tag
platform: linux
image_resource:
  type: docker-image
  source:
    # 2do: replace with small image with tar (strip-components) and jq
    # repository: realguess/jq
    repository: makeomatic/k8s-ci
    tag: "12102018"
inputs:
  - name: github-release
outputs:
  - name: image-meta
run:
  path: sh
  args:
  - -exc
  - |
    tar xzf ./github-release/source.tar.gz --strip-components 1
    NODE=`jq .node .mdeprc -r`
    VERSION=`cat ./github-release/version`
    echo "$NODE-$VERSION" > ./image-meta/tag
